on:
  push:
    branches:
      - 'main'

name: Publish documentation

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly

    steps:
      - uses: actions/checkout@v3.0.2
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - uses: actions-rs/cargo@v1.0.3
        with:
          command: doc
          args: --all --all-features

      - name: Deploy documentation
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          build_dir: target/doc
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#  vim: set ft=yaml ts=2 sw=2 tw=0 et :
